### ISSUE TITLE
"id" as field name getting populated with meta().id in the response

### ISSUE THREAD

**Issue by balaji-it** [spring-projects/spring-data-couchbase#1258]
The documents having "id as field name not getting populated with the correct value in the response via spring-data Couchbase.
The stored value for id field is getting replaced with document meta().id when we fetch data using the query below.
 
@Query("SELECT * FROM #{#n1ql.bucket} WHERE id = $1")
 
Example:
Below is the Document data stored in Couchbase: (meta().id => c00994b8-b547-4388-a549-e1543edbd9c8)
{
"id": "eeb7afa9-3ada-483d-ac1a-7efcf6e7b232",
“name”: “John”
}

Response object retrieved via NQL query above:
{
"id": "c00994b8-b547-4388-a549-e1543edbd9c8",
“name”: “John”
}

**Comment by mikereiche** [comment]
If the issue persists with documents inserted using spring-data-couchbase, please reopen.

**Comment by mikereiche** [comment]
See CBSE-10927

The issue is that decode uses property.isIdProperty() to determine if a field is the id field. It should use property == entity.getIdProperty().  This is the check that should be use everywhere instead of property.isIdPropery().

Also StringBasedN1qlParser.getProjectedFieldsInternal() needs to use property = entity.getIdProperty() otherwise it will not project the field name id that is not an IdProperty.
