### ISSUE TITLE
Enum with JsonValue in 5.X

### ISSUE THREAD

**Issue by abhijit911turbo** [spring-projects/spring-data-couchbase#1690]
public enum LaunchType {
    HARD("Hard"),
    SOFT("Soft");

    private final String name;

    @Override
    @JsonValue
    public String toString() {
        return name;
    }
}

In Spring data couchbase 4.X, Enums where persisted to database as HARD or SOFT
Once we upgraded to Spring data couchbase 5.X, Enums are persisted to database as Hard or Soft.

Why has the behaviour changed and can we move back to previous behaviour?

**Comment by mikereiche** [comment]
4.x was incorrectly serializing enums as their name (which would be HARD, SOFT in your case).

serializing was:
Enum.class.isAssignableFrom(value.getClass()) ? ((Enum<?>) value).name()

deserializing was:
              Enum.valueOf((Class<Enum>) target, value.toString());
              
This was not compatible with serializing/deserializing with the Couchbase Java SDK.

The issue was raised and fixed in https://github.com/spring-projects/spring-data-couchbase/issues/1617

Enums are now serialized and deserialized by the ObjectMapper (OtherConverters.EnumToObject and Boolean/Integer/StringToEnumConverter.  

If you want your LaunchType to be serialized as HARD, SOFT, then you can create a method that returns that and annotate it with @JsonValue.  Likewise, create a method annotated with @JsonCreator that takes those strings and returns the Enums.

@JsonValue
public String name(){
   return super.name(); // I suppose name.toUpperCase() would work as well.
  }
  
  @JsonCreator
  public LaunchType(String uppercaseName){ 
   for(LaunchType e:LaunchType.values()){
       if(values.name().equals(uppercaseName)){
           name = values.name; // the mixed-case name, not the uppercase name()
           return;
        }
    }
    throw SomeDerializationException(...);
 }
